
"use client"

import './globals.css'
import "next-english-node/dist/styles.css"; 
import { useStore } from '../store/useStore';
import { useEffect } from 'react';
import { registerIframeListener } from '../utils/messaging/receiver';
import { sendIframeReady } from '../utils/messaging/sender';
import { sendProgress} from '../utils/messaging/sender';
import { ACTIVITY_STATUS } from '../utils/messaging/constants.js';
import SingleTabGuard from "../components/SingleTabGuard";
import EmbeddedSessionGuard from "../components/EmbeddedSessionGuard";


export default function RootLayout({ children }) {


  const setSessionData = useStore((s) => s.setSessionData);
const sessionData = useStore((s) => s.sessionData);
const setLanguage = useStore((s) => s.setLanguage);
const setGuidedTour = useStore((s) => s.setGuidedTour);

useEffect(() => {

const cleanup = registerIframeListener({
onInit: (payload) => {
setSessionData(payload);
if (payload?.context?.lang) {
  setLanguage(payload.context.lang);
}
if (payload?.context?.guidedTour) {
  setGuidedTour(payload.context.guidedTour);
}
},
onLangChange: (lang) => {
  setLanguage(lang);
},
onBlocked: (detail) => {
  window.dispatchEvent(new CustomEvent("olabs-embed-block", { detail: detail ?? {} }));
},
});
sendIframeReady();
return cleanup;
}, []);

useEffect(() => {
  if (!sessionData) return;
  
  console.log("session logged"+sessionData+sessionData?.auth?.isAuthenticated)
  sendProgress({
    session: sessionData,
    progress: {
      text: "Simulation Started",
      percentage: 10,
      completionStatus: ACTIVITY_STATUS.COMPLETED,
    },
    stepId: "step-1",
    timeSpent: 20,
  });
  }, [sessionData]);


  return (
    <html lang="en">
      <body>
        <SingleTabGuard appName="This simulation" />
        <EmbeddedSessionGuard>{children}</EmbeddedSessionGuard>
      </body>
    </html>
  )
}

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
