export const MESSAGE_SOURCE = "OLABS_SIMULATION";


export const MESSAGE_TYPES = {
 IFRAME_READY: "IFRAME_READY",
 SIMULATION_INIT: "SIMULATION_INIT",
 SIMULATION_BLOCKED: "SIMULATION_BLOCKED",
 SIMULATION_READY_ACK: "SIMULATION_READY_ACK",
 SIMULATION_PROGRESS: "SIMULATION_PROGRESS",
 SIMULATION_SUBMIT: "SIMULATION_SUBMIT",
 LANG_CHANGE: "LANG_CHANGE",
 GUIDED_TOUR_COMPLETED: "GUIDED_TOUR_COMPLETED",


};


export const EXAM_MODE = {
 PRACTICE: "PRACTICE",
 SCORED: "SCORED",
};


export const ACTIVITY_STATUS = {
 STARTED: "STARTED",
 IN_PROGRESS: "IN_PROGRESS",
 COMPLETED: "COMPLETED",
 EXITED: "EXITED"
};


export const PARENT_ORIGIN = "*";
export const PROTOCOL_VERSION = "1.0.0";